# Generated by Django 6.1.1 on 2026-09-13 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('slug', models.SlugField(max_length=260, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('art', 'Art & culture'), ('music', 'Music'), ('food', 'Food & drink'), ('outdoors', 'Outdoors'), ('community', 'Community'), ('other', 'Something different')], default='other', max_length=24)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('venue', models.CharField(blank=True, max_length=240)),
                ('neighborhood', models.CharField(blank=True, max_length=120)),
                ('borough', models.CharField(blank=True, max_length=120)),
                ('official_url', models.URLField(max_length=1000, unique=True)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('price_label', models.CharField(blank=True, max_length=120)),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('fit_reason', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('top_pick', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=240)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='events.event')),
            ],
            options={
                'ordering': ['starts_at', 'pk'],
            },
        ),
    ]
