# Generated by Django 6.1.1 on 2026-09-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('price_min__gte', 0), ('price_min__isnull', True), _connector='OR'), name='event_min_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('price_max__gte', 0), ('price_max__isnull', True), _connector='OR'), name='event_max_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('price_max__gte', models.F('price_min')), ('price_min__isnull', True), ('price_max__isnull', True), _connector='OR'), name='event_price_order'),
        ),
    ]
