# Generated by Django 6.1.1 on 2026-09-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_event_min_nonnegative_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='occurrence',
            constraint=models.UniqueConstraint(fields=('event', 'source_key'), name='occurrence_source_unique'),
        ),
        migrations.AddConstraint(
            model_name='occurrence',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gte', models.F('starts_at')), ('ends_at__isnull', True), _connector='OR'), name='occurrence_time_order'),
        ),
    ]
