# Generated by Django 6.1.1 on 2026-09-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_occurrence_occurrence_source_unique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('art', 'Art & culture'), ('theater', 'Broadway & theater'), ('queer', 'Queer NYC'), ('tech', 'Tech, AI & finance'), ('comics', 'Comics, manga & anime'), ('gaming', 'Gaming'), ('books', 'Books & fiction'), ('fitness', 'Fitness'), ('music', 'Music'), ('food', 'Food & drink'), ('outdoors', 'Outdoors'), ('community', 'Community'), ('other', 'Something different')], default='other', max_length=24),
        ),
    ]
