# Generated by Django 6.1.1 on 2026-09-13 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
