# Generated by Django 6.1.1 on 2026-09-14 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_is_active_occurrence_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheaterDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('slug', models.SlugField(max_length=260, unique=True)),
                ('classification', models.CharField(choices=[('broadway', 'Broadway'), ('off_broadway', 'Off-Broadway'), ('other', 'Other NYC theater')], max_length=24)),
                ('venue', models.CharField(blank=True, max_length=240)),
                ('neighborhood', models.CharField(blank=True, max_length=120)),
                ('official_url', models.URLField(max_length=1000, unique=True)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('verified_at', models.DateTimeField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('classification', 'title', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='TheaterOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=240)),
                ('label', models.CharField(max_length=240)),
                ('price_label', models.CharField(max_length=160)),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fees_included', models.BooleanField(blank=True, null=True)),
                ('restrictions', models.TextField(blank=True)),
                ('eligible_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('official_url', models.URLField(max_length=1000)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='events.theaterdeal')),
            ],
            options={
                'ordering': ('price_min', 'source_key'),
                'constraints': [models.UniqueConstraint(fields=('deal', 'source_key'), name='theater_offer_source_unique'), models.CheckConstraint(condition=models.Q(('price_min__gte', 0), ('price_min__isnull', True), _connector='OR'), name='theater_offer_min_nonnegative'), models.CheckConstraint(condition=models.Q(('price_max__gte', models.F('price_min')), ('price_min__isnull', True), ('price_max__isnull', True), _connector='OR'), name='theater_offer_price_order')],
            },
        ),
    ]
